version: "3.8"
services:
    db:
        image: "postgres:14.2"
        container_name: database
        ports:
         - "5432:5432"
        volumes:
         - ./pgdata:/var/lib/postgresql/data
        environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=pw25s
        networks:
         - apps
        restart: always
networks:
  apps:
    name: apps